Initial commit
wirenboard/wb-connection-manager pull request #1
Opened 2022-09-02 09:12 UTC by KraPete

Периодически проверяю активное соединение и доступность внешнего ресурса через него.
Если ресурс не доступен, закрываю соединение.
Иду дальше по списку соединений и пытаюсь открыть те, что имеют меньший приоритет.
Если получилось открыть соединение с большим приоритетом, чем текущее активное, то закрываю менее приоритетные.
Пока все таймауты и список соединений захардкодил, т.к. это прототип.

2022-09-02 14:17 UTC, evgeny-boger reviewed
а у NM разве нет встроенного механизма проверять доступность интернета? В любом случае, это надо делать не пингом, а что-то забирать по HTTP и проверять что отдалось

2022-09-05 11:23 UTC, KraPete commented
Переделал на встроенную проверку от NM.

2022-09-06 08:16 UTC, webconn requested changes
Надо вычистить ловлю исключений, тут полная путаница и в итоге много исключений проглатывается. То же самое касается логов, надо сделать так, чтобы в обычном режиме работы на каждую итерацию количество и качество логов было адекватным.

Ещё можно сразу сделать сервис для `systemd`, при тестировании 100% забудут запустить.

И jenkinsfile добавить с `buildDebArchAll()`.

2022-09-06 08:16 UTC, webconn commented on setup.py
> +      description="network connections management service for WirenBoard devices",
`Wiren Board` в два слова лучше. Давно хочу в этом порядок навести, начну хотя бы с новых репозиториев :)

2022-09-06 08:16 UTC, webconn commented on debian/control
> +Description:  Wirenboard network connections manager.
`Wiren Board` в два слова с больших букв, и точка в конце не нужна

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/modem_manager.py
> +        return False
Тут как будто бы исключение напрашивается, ситуация нештатная, но никак не обрабатывается

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/network_manager.py
> +        return None
Тоже просится исключение

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/network_manager.py
> +        return None
Исключение

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/network_manager.py
> +            logging.debug('Device for connection "%s" is not found', settings["connection"]["id"])
Это сообщение в логах никому не поможет, давай сразу уберём. Лучше пусть метод бросает исключение, если ничего не нашёл (хотя `find_device_by_param` это должен бы сделать сам)

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +def check_ip4_connectivity(nm, active_connection_path):
Это напрашивается на переезд в `network_manager.py`

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            logging.debug(ex)
Тут лучше ограничить множество проверяемых исключений до тех, которые ты ожидаешь. И из лога не будет понятно, что происходит, просто так будут сыпаться записи про исключения

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            if dev:
Если `find_device_for_connection` всегда будет возвращать что-то хорошее или бросать исключение, тут станет меньше кода

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    return None
Исключение, здесь и дальше по файлу, не буду в каждое место больше писать

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            return False
Почему тут падение, а не продолжаем ожидать? Код такой же, как выше, логи такие же вывалятся, непорядок. Опять же, стоит уточнить, какие исключения тут ожидаются в плохих ситуациях

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +                # Connection object is already unexported
Вот это можно было бы в лог вывести

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +        return ActivateConnectionResult(None, False)
Странно тут вторым аргументом `False`, если ожидается id. Лучше `None` для этого использовать

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    logging.basicConfig(level=logging.DEBUG)
У тебя всё логгирование в `debug` здесь, стоит подраскидать, хотя бы ошибки выделить

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    while True:
Не будет возможности запустить эту штуку разово? Может, триггерить по сигналу или ещё как-нибудь, чтобы отлаживаться было попроще

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            logging.debug(ex)
Очень плохо в таком виде, некоторые исключения могут быть серьёзными. Лучше падать, и писать в `logging.critical(exc_info=True)`, так стектрейс сохранится в логах

2022-09-06 08:16 UTC, webconn commented on debian/wb-connection-manager.install
> +bin/wb-connection-manager /usr/bin
Я бы это в `/usr/lib/wb-connection-manager` положил, чтобы не засорять пространство имён в `$PATH`

2022-09-06 08:16 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +CHECK_PERIOD = datetime.timedelta(seconds=5)
Думаю, раз в минуту было бы за глаза

2022-09-06 09:31 UTC, KraPete commented on wb/connection_manager/modem_manager.py
> +        return False
В этом и смысл, нет никаких разумных способов что-то сделать в этой ситуации. Максимум в лог написать, который никто не читает. Интересен только факт, удалось переключить симку или нет. Что даст исключение?

2022-09-06 09:32 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +        return None
Зачем? Это нормальный ход работы программы. Либо что-то нашли, либо не нашли. Всё явно.

2022-09-06 09:33 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +        return None
То же самое, нормальный ход работы программы.

2022-09-06 09:36 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +            logging.debug('Device for connection "%s" is not found', settings["connection"]["id"])
`find_device_by_param` ни в коем случае не должен выкидывать исключения.
Сообщение в лог, да, стоит убрать. в вызывающий код.

2022-09-06 09:39 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            logging.debug(ex)
В этом и проблема, я не знаю ничего об исключениях, которые могут быть здесь. Да и в общем-то мне глубоко наплевать на них. Ни я, ни кто другой ничего с ними сделать не сможет. Важен сам факт появилось устройство подходящее для этого содинения или нет.

2022-09-06 09:40 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            if dev:
Тут ничего абсолютно не изменится. Т.к. нормальная ситауция, когда ничего не нашли, и нормальная ситауция, кодга в процессе поиска что-то изменилось в dbus и промежуточные объекты стали невалидные, о чем сообщяется через исключения.

2022-09-06 09:41 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    return None
Не буду нигде делать исключения, т.к. не понимаю, что они дадут, кроме спагетти.

2022-09-06 09:45 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            return False
Да не знаю я ничего об исключениях, которые могут тут выпасть. Это магия, которая стреляет неожиданно. Но я не хочу обрабатывать их где-то там. Мне тут важен факт, перешло соединение в активированное состояние или нет. 
А вообще, тут абсолютно одинаково, хоть продолжать ждать, хоть выходить. Т.е. хз что сломалось, и как реагировать.

2022-09-06 09:46 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +                # Connection object is already unexported
Это штатная ситуация. В 99% слачаев мы будем идти по этой ветке.

2022-09-06 09:46 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +        return ActivateConnectionResult(None, False)
Пропустил, исправлю

2022-09-06 09:47 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    logging.basicConfig(level=logging.DEBUG)
Я хотел это обсудить, т.к. не понимаю что выводить в `info`, а что в `debug`

2022-09-06 09:48 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    while True:
Кто будет этот сигнал выдавать? Если есть предложения, давай, сделаю.

2022-09-06 09:50 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +CHECK_PERIOD = datetime.timedelta(seconds=5)
Я вообще хотел эти константы вынести в настройки, когда будет понятно где их хранить, и что надо настраивать.

2022-09-06 10:00 UTC, KraPete commented on setup.py
> +      description="network connections management service for WirenBoard devices",
Поправил

2022-09-06 10:01 UTC, KraPete commented on debian/control
> +Description:  Wirenboard network connections manager.
Поправил

2022-09-06 10:21 UTC, KraPete commented on debian/wb-connection-manager.install
> +bin/wb-connection-manager /usr/bin
Убрал

2022-09-06 10:21 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +def check_ip4_connectivity(nm, active_connection_path):
Перенёс

2022-09-06 10:30 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            logging.debug(ex)
Сделал. Но так-то разницы почти нет, либо мы тут пишем исключения и дальше крутимся, либо systemd нас перезапустит.

2022-09-06 10:36 UTC, KraPete commented
> Надо вычистить ловлю исключений, тут полная путаница и в итоге много исключений проглатывается. То же самое касается логов, надо сделать так, чтобы в обычном режиме работы на каждую итерацию количество и качество логов было адекватным.
> 
> Ещё можно сразу сделать сервис для `systemd`, при тестировании 100% забудут запустить.
> 
> И jenkinsfile добавить с `buildDebArchAll()`.

1. С исключениями вопрос религиозный, я не вижу смысла в них здесь.
2. "надо сделать так, чтобы в обычном режиме работы на каждую итерацию количество и качество логов было адекватным" == "я не знаю как надо, но как сейчас мне не нравится". Так вот, я тоже не знаю как надо, потому всё в debug и оставил, чтоб раздражало ревьюверов, вдруг кто-то какую-то конкретику выскажет. Вывел в debug ту информацию, что использовал сам при отладке. Что нужно в логе пользователю - хз. Приму любые конкретные предложения.

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/modem_manager.py
> +        return False
То, что в лог напишется в том месте, где всё взаимодействие с пользователем происходит, и это не будет размазано по всему коду. В тому же стектрейсы - это удобно при отладке. Вот на примере этой функции могу сказать, что у тебя при ей вызове потерялась информация о том, что симка не переключилась. В лог не написал, просто вернул, что новое соединение None (и это не один раз в вызывающей функции происходит, так что снаружи не отличишь).

В питоне на исключениях не экономят, так что странно не пользоваться.

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/network_manager.py
> +        return None
В вызывающей функции у тебя дальше по стеку в этом случае передаётся пустое значение. Если это ок по логике программы - ну ладно, но если подразумевалось, что программа однажды переключит соединение, то то, что она его не нашла - ситуация нештатная. А узнаем мы это через логи уровня debug

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    while True:
Можно запускать этот же скрипт с аргументом, по которому он найдёт PID и отправит сигнал

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    logging.basicConfig(level=logging.DEBUG)
Как минимум есть места, которые просятся в явный error. Думаю, что в info надо выводить только инфу о том, что соединение переключилось, а всё остальное (кроме ошибок) оставить в debug. Во всяком случае это то, что я как пользователь хотел бы видеть в логе

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            return False
Пример исключения, которое ты тут зря прожевал - `KeyboardInterrupt` :)

У тебя тут что-то стреляло? Если это из dbus - ну поймай их исключение. А если любое исключение здесь означает сломанное состояние дальше - тогда и ловить его здесь не надо, оно поймается на самом высоком уровне и всё можно будет начать сначала

2022-09-06 11:05 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    return None
Спагетти больше дают if на каждом шагу для проверки ошибочных значений. Исключения можно централизованно поймать выше всего по стеку и обработать аккуратно

2022-09-06 11:05 UTC, webconn commented on debian/wb-connection-manager.install
> +bin/wb-connection-manager /usr/lib
В `/usr/lib/<имя пакета>`, иначе там не принято

2022-09-06 11:18 UTC, KraPete commented on wb/connection_manager/modem_manager.py
> +        return False
Причём здесь соединение? Конкретно тут или переключилась симка или нет.

2022-09-06 11:24 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +        return None
Бррр. А если упадёт X-сервер, тут тоже нет про это информации. Зачем придумывать что-то? Тут всё просто, или нашли или не нашли, другого не подразумевается.

2022-09-06 11:26 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    return None
Говорю ж, вопрос религиозный.

2022-09-06 11:44 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            return False
Опять магия, у меня тут dbus, а ты про клаву. Вопрос на 100$: "Сможешь выписать все возможные исключения для этой функции?", чтоб я красиво обработал только нужные?
Здесь отражается моё желание наплевать на все исключения, и знать только активировалось соединение или нет за определённый промежуток времени. Не надо придумывать гипотетических ситуаций, это код для конкретной одной задачи.

2022-09-06 11:55 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    logging.basicConfig(level=logging.DEBUG)
"Как минимум есть места, которые просятся в явный error." -  можно пальцем ткнуть.
Факт активации соединения добавлю в `info`.

2022-09-06 11:57 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    while True:
А ещё сложнее получится? ;)
Тогда уж сделать параметр командной строки для запуска один раз.

2022-09-06 12:08 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +            return False
Так если бы с клавой ничего не случилось, я бы ничего против не имел. Но теперь, когда исполняется код в try, ты не можешь остановить скрипт через ctrl-c, вместо этого ты проигнорируешь это событие. Ты в итоге, не представляя, что тебе функция может вывалить, по умолчанию построил бетонную стену вокруг неё, как раз придумав гипотетическую ситуацию. Можно было просто её не строить и всё бы работало :)

2022-09-06 12:08 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +                # Connection object is already unexported
Окей

2022-09-06 12:08 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    while True:
Можно и так, если два одновременно запущенных скрипта между собой не поссорятся

2022-09-06 12:08 UTC, webconn commented on wb/connection_manager/network_manager.py
> +        return None
Так а почему мы можем не найти? Разве на штатно работающем WB тут не должно всё всегда само находиться?

2022-09-06 12:08 UTC, webconn commented on wb/connection_manager/connection_manager.py
> +    return None
Как минимум, у тебя прямо сейчас целая куча мест, где что-то "не нашлось", обрабатывается так, как будто это порядок вещей. Это точно порядок вещей?

2022-09-06 12:14 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +        return None
Ну вбил я руками в настройки название с ошибкой. Теперь надо чтоб весь сервис валился? Ты опять придумываешь какие-то гипотетические ситуации. Штатное поведение функции "найти что-то" - это найти или не найти. Не надо тут исключений.

2022-09-16 07:49 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +            return False
`ctrl-c` обрабатывается через сигналы и нормально из цикла выходит

2022-09-16 07:50 UTC, KraPete commented on debian/wb-connection-manager.install
> +bin/wb-connection-manager /usr/lib
Сделал

2022-09-27 13:36 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +def get_active_connections(connection_ids, active_connections):
мб как-то paths в названии отразить?

2022-09-27 13:46 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +def get_active_connections(connection_ids, active_connections):
Не совсем понял. Можешь пример написать?

2022-09-27 13:53 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +class ConnectionStateFilter(logging.Filter):
комментик бы, зачем фильтр

2022-09-27 13:53 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +    logging.debug('Waiting for connection activation')
таймаут бы сюда

2022-09-27 13:54 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +    return False
ну я, на самом деле, тоже за Никитин подход (с ошибками)
здесь и дальше вместо `True/False` - `raise КоннекшенНеПоднялсяЕррор("подождали N секунд - всё плохо")`

это не сильно сложнее, зато сильно понятнее

2022-09-27 13:54 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +def wait_connection_deactivation(nm, cn_path, timeout):
похоже на копипасту предыдущего
мб в какую-нибудь абстракцию?

2022-09-27 13:54 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +        time.sleep(1)
в переменную бы
и остальное тоже

2022-09-27 13:54 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +        dev = wait_device_for_connection(nm, cn_obj, datetime.timedelta(seconds=30))
как-то неочевидно выглядит datetime в функцию носить
мб передавать секунды, и уже внутри timedelta делать?

2022-09-27 13:54 UTC, vdromanov commented on wb/connection_manager/connection_manager.py
> +    if cn_id in connection_up_time:
на мой вкус - можно было
`return connection_up_time.get(connection_up_time, 1970_год) + CONNECTION_ACTIVATION_RETRY_TIMEOUT > datetime.datetime.now()`

2022-09-27 13:55 UTC, vdromanov commented on wb/connection_manager/network_manager.py
> +        return str(settings["connection"]["id"])
а вот dbus, кстати, точно всегда возвращает словарь со всеми полями?

мб имеет смысл что-то вроде `return str(settings.get("connection", {}).get("id"))` здесь и вообще везде, где мы полагаемся на поля всякого, прилетевшего извне

2022-09-27 14:06 UTC, vdromanov reviewed
В целом - для прототипа вполне себе хорошо. Для продакшена - кажется, надо будет порефакторить.

Чего хотелось бы финально:
- строчки не по кодстайлу проскакивают
- свои ошибки и raise их вместо return True/False/None. Сейчас - выглядит (надеюсь, только выглядит!!) довольно хрупко и неудобно для отладки
- как-то обезопасить прилетающее из dbus
- какое-нибудь логгирование поинтересней: свой логгер библиотечке, его включение/отключение снаружи (?)

Сейчас - предлагаю выкатить в тестинг, т.к. systemd спасёт от падений в случае чего

2022-09-27 14:46 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +    logging.debug('Waiting for connection activation')
Опять не понял. Что сделать с таймаутом? :) В диагностическое сообщение его вывести?

2022-09-27 14:49 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +def wait_connection_deactivation(nm, cn_path, timeout):
Ну вот мне в одном месте надо поймать ваше любимое исключение, а в другом месте нет. Так что максимум могу цикл абстаргировать. Но надо ли оно?

2022-09-27 14:50 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +        time.sleep(1)
Остальное это что? :)

2022-09-27 14:55 UTC, KraPete commented on wb/connection_manager/connection_manager.py
> +        dev = wait_device_for_connection(nm, cn_obj, datetime.timedelta(seconds=30))
Вообще как тут "правильно" действовать. Я хочу, чтобы в функцию заходил временной интервал, который задаёт максимальное время ожидания?
В C++ всё просто, я объявляю функцию, у которой параметр объект класса "временной интервал". Любой использующий её сразу видит, что я хочу. Плюс компилятор бьёт по рукам, когда вместо временного интервала суют килограммы. И самое приятное, что не надо читать код функции, чтобы всё понять.
Как мне сделать тут так же, чтобы по объявлению функции было ясно, что это временной интервал, не заставляя никого вчитываться в код?

2022-09-27 14:58 UTC, KraPete commented on wb/connection_manager/network_manager.py
> +        return str(settings["connection"]["id"])
Так. Вы уж решитесь, вы за исключения или за возврат `None`

2022-09-27 15:22 UTC, KraPete commented
Можно аргументированно, с примерами, прямо из моего кода, в тех местах, где вы хотите исключения, что станет лучше?
Вот, если честно, я пока только общие фразы вижу.
Хочу сравнение. Например, вот у меня так, а если бы было так с исключениями, то вот кода меньше, или вот такие неучтённые ситуации обрабатываются или что-то ещё, что реально можно пощупать.
Пока я вижу только клёвые стектрейсы, но это ж фиаско. Приложение не должно вываливать стектрейсы, оно должно культурно по-человечески сказать пользователю, что не смогло что-то сделать, а в идеале ещё и подсказать как исправить ситуацию.
Я сделал возврат `True\False\None`, потому что это нормальное поведение функций, я не хочу каждую строку обрамлять через `try`, это куча невнятного кода. Там, где я не ожидаю в нормальном течении программы ошибок, там используются исключения.
Я уже писал, что исключени или коды возврата - религиозный вопрос. В одних ситуациях удобнее одно, в других - другое. Вы сами сначала решитесь, когда и что использовать. А лучше в codestyle впишите. ;)

2022-10-21 08:59 UTC, webconn commented
Этот PR ведь больше не нужен из-за https://github.com/wirenboard/wb-nm-helper/pull/1 ?

2022-10-21 09:41 UTC, closed without merging